[package]
name = "with_generics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0"}
quote = { version = "1.0" }
syn = { version = "2.0.100", features = ["full"] }
